---
- name: Install remote facts
  hosts: centos7-2
  become: yes
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Ensure that the remote directory exists
      file: 
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    
    - name: Install new custom facts
      copy:
        src: "{{ facts_file }}" 
        dest: "{{ remote_dir }}"
