---
- name: Ensure that the database and web servers are installed
  yum:
    name: 
      - "{{ ansible_local.custom.pacakages.db_package }}"
      - "{{ ansible_local.custom.pacakages.web_package }}"
    state: latest

- name: Ensure that the database server is enabled and started
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    state: started
    enabled: true

- name: Ensure that the web server is enabled and started
  service:
    name: "{{ ansible_local.custom.services.web_service }}"
    state: started
    enabled: true