# This YAML file is part of a Red Hat Self-Paced Lab (RHSPL) held during Red Hat Summit 2018.
# It is used for the chapter on "Implementing Task Control"
#
#############################################################################################################
---
- yum:
    name: "{{ fw_package }}"
    state: latest
  tags: production

- service:
    name: "{{ fw_service }}"
    state: started
    enabled: true
  tags: production

- firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - http 
    - https 
  tags: production